/**
 *
 * 无接口前缀工程
 */
const PREFIX = `jsh-study-service-exchange${process.env.VUE_APP_SERVER_SUFFIX}`;
export const Exchange = {
  // 课程详情-客户端-已学习-导出
  exportAradyLearn: `${PREFIX}/api/exchange/page/college/base-detail/export-study-info`,
  exportZhjLearn: `${PREFIX}/api/exchange/page/college/base-detail/export-study-info-status`,
  exportEndLearn: `${PREFIX}/api/exchange/page/college/base-detail/export-study-info-task`,
  // 课程详情-客户端-已学习-导出
  classExportAradyLearn: `${PREFIX}/api/exchange/page/class/course/export-list-study-info`,
  classExportZhjLearn: `${PREFIX}/api/exchange/page/class/course/export-list-study-info-status`,
  classExportEndLearn: `${PREFIX}/api/exchange/page/class/course/export-list-study-info-task`,
  // 课程详情-客户端-未学习-导出
  unstudyArady: `${PREFIX}/api/exchange/page/college/base-detail/export-unstudy-info`,
  unstudyZhiL: `${PREFIX}/api/exchange/page/college/base-detail/export-unstudy-info-status`,
  unstudyEnd: `${PREFIX}/api/exchange/page/college/base-detail/export-unstudy-info-task`,
  // 课程详情-客户端-未学习-导出
  classUnstudyArady: `${PREFIX}/api/exchange/page/class/course/export-list-unstudy-info`,
  classUnstudyZhiL: `${PREFIX}/api/exchange/page/class/course/export-list-unstudy-info-status`,
  classUnstudyEnd: `${PREFIX}/api/exchange/page/class/course/export-list-unstudy-info-task`,
  // 课程详情-直销员端-已学习-导出
  exportSellerAlreadyLearn: `${PREFIX}/api/exchange/page/college/base-detail/export-zxy-study-info`,
  exportSellerAlreadyLearnStatus: `${PREFIX}/api/exchange/page/college/base-detail/export-zxy-study-info-status`,
  exportSellerAlreadyLearnTask: `${PREFIX}/api/exchange/page/college/base-detail/export-zxy-study-info-task`,
  // 课程详情-直销员端-未学习-导出
  exportSellerNoLearn: `${PREFIX}/api/exchange/page/college/base-detail/export-zxy-unstudy-info`,
  exportSellerNoLearnStatus: `${PREFIX}/api/exchange/page/college/base-detail/export-zxy-unstudy-info-status`,
  exportSellerNoLearnTask: `${PREFIX}/api/exchange/page/college/base-detail/export-zxy-unstudy-info-task`,
  // 课程详情-报名清单（客户端）-导出
  exportUpList: `${PREFIX}/api/exchange/page/college/export-sign-up-list`,
  // 课程详情-报名清单（客户端）-查询状态
  getSignUpDownloadTemplateStatus: `${PREFIX}/api/exchange/page/college/get-sign-up-download-template-status`,
  // 课程详情-报名清单（客户端）-导出提交
  listSignUpDownloadTemplateTask: `${PREFIX}/api/exchange/page/college/list-sign-up-download-template-task`,
  // 课程详情-报名清单（直销员端）-导出
  exportSellerList: `${PREFIX}/api/exchange/page/college/export-zxy-sign-up-list`,
  // 课程详情-报名清单（直销员端）-查询状态
  getSignUpDownloadSellerTemplateStatus: `${PREFIX}/api/exchange/page/college/get-zxy-sign-up-download-template-status`,
  // 课程详情-报名清单（直销员端）-导出提交
  listSignUpDownloadSellerTemplateTask: `${PREFIX}/api/exchange/page/college/list-zxy-sign-up-download-template-task`,
  //学员范围-下载模版
  downloadTmp: `${PREFIX}/api/exchange/page/college/management/download-template`,
  //学员范围-下载模版-直销员
  downloadTmpSale: `${PREFIX}/api/exchange/page/college/management/download-template-zxy`,
  //学员范围-导出学员信息
  exportCustomerData: `${PREFIX}/api/exchange/page/college/management/export-cust-throw`,
  exportCustomerDataStatus: `${PREFIX}/api/exchange/page/college/management/get-cust-throw-download-template-status`,
  exportCustomerDataTask: `${PREFIX}/api/exchange/page/college/management/list-cust-throw-download-template-task`,
  //学员范围-导出学员信息-直销员
  exportCustomerDataSale: `${PREFIX}/api/exchange/page/college/management/export-cust-throw-zxy`,
  exportCustomerDataStatusSale: `${PREFIX}/api/exchange/page/college/management/get-cust-throw-download-template-status-zxy`,
  exportCustomerDataTaskSale: `${PREFIX}/api/exchange/page/college/management/list-cust-throw-download-template-task-zxy`,
  //广告详情-导出-客户端
  advertDetailExport: `${PREFIX}/api/exchange/page/college/management/export-advert-org`,
  advertExportStatus: `${PREFIX}/api/exchange/page/college/management/export-advert-org-status`,
  advertExportTask: `${PREFIX}/api/exchange/page/college/management/export-advert-org-task`,
  //广告详情-导出-直销员端
  exportAdvertOrgZxy: `${PREFIX}/api/exchange/page/college/management/export-advert-org-zxy`,
  exportAdvertOrgZxyStatus: `${PREFIX}/api/exchange/page/college/management/export-advert-org-zxy-status`,
  exportAdvertOrgZxyTask: `${PREFIX}/api/exchange/page/college/management/export-advert-org-zxy-task`,
  // 讲师列表信息导出
  exportLecturerList: `${PREFIX}/api/exchange/page/college/base-detail/export-lecturer`,
  getExportLecturerStatus: `${PREFIX}/api/exchange/page/college/base-detail/export-lecturer-status`,
  exportLecturerListTask: `${PREFIX}/api/exchange/page/college/base-detail/export-lecturer-task`,
  // 学员列表信息导出-客户端
  exportStudentList: `${PREFIX}/api/exchange/page/customer/export-customer`,
  exportStudentListStatus: `${PREFIX}/api/exchange/page/customer/export-customer-status`,
  exportStudentListTask: `${PREFIX}/api/exchange/page/customer/export-customer-task`,
  // 学员列表信息导出-员工端
  exportCustomerYg: `${PREFIX}/api/exchange/page/customer/export-customer-yg`,
  exportCustomerStatusYg: `${PREFIX}/api/exchange/page/customer/export-customer-status-yg`,
  exportCustomerYgTask: `${PREFIX}/api/exchange/page/customer/export-customer-yg-task`,
  // 学员列表信息导出-直销员端
  exportCustomerZxy: `${PREFIX}/api/exchange/page/customer/export-customer-zxy`,
  exportCustomerStatusZxy: `${PREFIX}/api/exchange/page/customer/export-customer-status-zxy`,
  exportCustomerZxyTask: `${PREFIX}/api/exchange/page/customer/export-customer-zxy-task`,
  // 学员列表信息导出-售后端
  exportCustomerHcc: `${PREFIX}/api/exchange/page/customer/export-customer-hcc`,
  exportCustomerStatusHcc: `${PREFIX}/api/exchange/page/customer/export-customer-status-hcc`,
  exportCustomerHccTask: `${PREFIX}/api/exchange/page/customer/export-customer-hcc-task`,
  // 学员分组信息导出-客户端
  exportStudentGroupList: `${PREFIX}/api/exchange/page/grouping/export-customer`,
  exportStudentGroupListStatus: `${PREFIX}/api/exchange/page/grouping/export-customer-status`,
  exportStudentGroupListTask: `${PREFIX}/api/exchange/page/grouping/export-customer-task`,
  // 学员分组信息导出-直销员端
  exportStudentGroupSaleList: `${PREFIX}/api/exchange/page/grouping/export-customer-zxy`,
  exportStudentGroupSaleListStatus: `${PREFIX}/api/exchange/page/grouping/export-customer-status-zxy`,
  exportStudentGroupSaleListTask: `${PREFIX}/api/exchange/page/grouping/export-customer-task-zxy`,
  // 课程统计报表导出
  exportCourseStatisticReport: `${PREFIX}/api/exchange/page/course-summary-report/export-course-summary`,
  exportCourseStatisticReportStatus: `${PREFIX}/api/exchange/page/course-summary-report/export-course-summary-download-template-status`,
  exportCourseStatisticReportTask: `${PREFIX}/api/exchange/page/course-summary-report/export-course-summary-download-template-task`,
  // 课程明细报表导出
  exportCourseDetailReport: `${PREFIX}/api/exchange/page/course-summary-detail-report/export-course-summary-detail`,
  exportCourseDetailReportStatus: `${PREFIX}/api/exchange/page/course-summary-detail-report/export-course-summary-detail-download-template-status`,
  exportCourseDetailReportTask: `${PREFIX}/api/exchange/page/course-summary-detail-report/export-course-summary-detail-download-template-task`,
  // 学习统计报表导出
  exportLearningStatisticReport: `${PREFIX}/api/exchange/page/study-summary-report/export-study-summary`,
  exportLearningStatisticReportStatus: `${PREFIX}/api/exchange/page/study-summary-report/export-study-summary-download-template-status`,
  exportLearningStatisticReportTask: `${PREFIX}/api/exchange/page/study-summary-report/export-study-summary-download-template-task`,
  // 学习明细报表导出
  exportLearningDetailReport: `${PREFIX}/api/exchange/page/study-summary-detail-report/export-study-detail-summary`,
  exportLearningDetailReportStatus: `${PREFIX}/api/exchange/page/study-summary-detail-report/export-study-detail-summary-download-template-status`,
  exportLearningDetailReportTask: `${PREFIX}/api/exchange/page/study-summary-detail-report/export-study-detail-summary-download-template-task`,
  //机构运营-bannerr管理-广告详情-导出-客户端
  exportBannelCustThrow: `${PREFIX}/api/exchange/page/general/bannel/export-bannel-cust-throw`,
  getBannelDownloadTemplateStatus: `${PREFIX}/api/exchange/page/general/bannel/get-bannel-download-template-status`,
  listBannelDownloadTemplateTask: `${PREFIX}/api/exchange/page/general/bannel/list-bannel-download-template-task`,
  //机构运营-bannerr管理-广告详情-导出-直销员
  exportBannelCustThrowZxy: `${PREFIX}/api/exchange/page/general/bannel/export-bannel-cust-throw-zxy`,
  getBannelZxyDownloadTemplateStatus: `${PREFIX}/api/exchange/page/general/bannel/get-bannel-zxy-download-template-status`,
  listBannelZxyDownloadTemplateTask: `${PREFIX}/api/exchange/page/general/bannel/list-bannel-zxy-download-template-task`,
  // 课程详情-课程统计-作业批改情况-导出
  exporthomeworkinfo: `${PREFIX}/api/exchange/page/operate/base-detail/export-home-work-info`,
  exporthomeworkinfostatus: `${PREFIX}/api/exchange/page/operate/base-detail/export-home-work-info-status`,
  exporthomeworkinfotask: `${PREFIX}/api/exchange/page/operate/base-detail/export-home-work-info-task`,
  // 课程详情-课程统计-作业批改情况-导出
  classexporthomeworkinfo: `${PREFIX}/api/exchange/page/class/course/export-list-home-work-info`,
  classexporthomeworkinfostatus: `${PREFIX}/api/exchange/page/class/course/export-list-home-work-info-status`,
  classexporthomeworkinfotask: `${PREFIX}/api/exchange/page/class/course/export-list-home-work-info-task`,
  // 课程详情-作业管理列表-导出
  exporthomeworksubmit: `${PREFIX}/api/exchange/page/operate/base-detail/export-homework-submit`,
  exporthomeworksubmitstatus: `${PREFIX}/api/exchange/page/operate/base-detail/export-homework-submit-status`,
  exporthomeworksubmittask: `${PREFIX}/api/exchange/page/operate/base-detail/export-homework-submit-task`,
  // 作业管理列表-导出
  exportHomeworkList: `${PREFIX}/api/exchange/page/operate/home-work/export-home-work-list`,
  exportHomeworkListStatus: `${PREFIX}/api/exchange/page/operate/home-work/export-home-work-list-status`,
  exportHomeworkListTask: `${PREFIX}/api/exchange/page/operate/home-work/export-home-work-list-task`,
  // 作业管理列表直销员-导出
  exportHomeworkListzxy: `${PREFIX}/api/exchange/page/operate/home-work/export-home-work-list-zxy`,
  exportHomeworkListStatuszxy: `${PREFIX}/api/exchange/page/operate/home-work/export-home-work-list-status-zxy`,
  exportHomeworkListTaskzxy: `${PREFIX}/api/exchange/page/operate/home-work/export-home-work-list-task-zxy`,
  // 报名明细-导出
  exportSignUpReport: `${PREFIX}/api/exchange/page/operate/sign-up/export-sign-up-report`,
  exportSignUpReportStatus: `${PREFIX}/api/exchange/page/operate/sign-up/export-sign-up-report-status`,
  exportSignUpReportTask: `${PREFIX}/api/exchange/page/operate/sign-up/export-sign-up-report-task`,
  // 考试统计报表-导出
  exportExamReport: `${PREFIX}/api/exchange/page/operate/exam/export-exam-report`,
  exportExamReportStatus: `${PREFIX}/api/exchange/page/operate/exam/export-exam-report-status`,
  exportExamReportTask: `${PREFIX}/api/exchange/page/operate/exam/export-exam-report-task`,
  // 考试统计报表-导出
  classExportExamReport: `${PREFIX}/api/exchange/page/class/course/export-list-exam-info`,
  classExportExamReportStatus: `${PREFIX}/api/exchange/page/class/course/export-list-exam-info-status`,
  classExportExamReportTask: `${PREFIX}/api/exchange/page/class/course/export-list-exam-info-task`,
  // 课程学习进度跟进报表-未学习-导出-客户端
  exportStudentUnstudyReport: `${PREFIX}/api/exchange/page/college/base-detail/export-student-unstudy-report`,
  exportStudentUnstudyReportStatus: `${PREFIX}/api/exchange/page/college/base-detail/export-student-unstudy-report-status`,
  exportStudentStudyReportUnStudy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-unstudy-report-task`,
  // 课程学习进度跟进报表-未学习-导出-直销员端
  exportStudentUnstudyReportZxy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-unstudy-report-zxy`,
  exportStudentUnstudyReportStatusZxy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-unstudy-report-status-zxy`,
  exportStudentUnstudyReportTaskZxy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-unstudy-report-task-zxy`,
  // 课程学习进度跟进报表-已学习-导出-客户端
  exportStudentStudyReport: `${PREFIX}/api/exchange/page/college/base-detail/export-student-study-report`,
  exportStudentStudyReportStatus: `${PREFIX}/api/exchange/page/college/base-detail/export-student-study-report-status`,
  exportStudentStudyReportTask: `${PREFIX}/api/exchange/page/college/base-detail/export-student-study-report-task`,
  // 课程学习进度跟进报表-已学习-导出-直销员端
  exportStudentStudyReportZxy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-study-report-zxy`,
  exportStudentStudyReportStatusZxy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-study-report-status-zxy`,
  exportStudentStudyReportTaskZxy: `${PREFIX}/api/exchange/page/college/base-detail/export-student-study-report-task-zxy`,
  // 班级管理-班级按指定学员导出
  exportClassCustThrow: `${PREFIX}/api/exchange/page/class/management/export-class-cust-throw`,
  exportClassCustThrowStatus: `${PREFIX}/api/exchange/page/class/management/export-class-cust-throw-status`,
  exportClassCustThrowTask: `${PREFIX}/api/exchange/page/class/management/export-class-cust-throw-task`,

  // 考试详情-未考试学员导出
  exportUnexamList: `${PREFIX}/api/exchange/page/class/exam/export-unexam-list`,
  exportUnexamStatus: `${PREFIX}/api/exchange/page/class/exam/export-unexam-status`,
  exportUnexamTask: `${PREFIX}/api/exchange/page/class/exam/export-unexam-task`,
  // 考试详情-考试学员导出
  exportExamList: `${PREFIX}/api/exchange/page/class/exam/export-exam-list`,
  exportExamStatus: `${PREFIX}/api/exchange/page/class/exam/export-exam-status`,
  exportExamTask: `${PREFIX}/api/exchange/page/class/exam/export-exam-task`,

  // 考试详情-考试学员导出
  exportClassStudent: `${PREFIX}/api/exchange/page/class/management/export-class-student`,
  exportClassStudentStatus: `${PREFIX}/api/exchange/page/class/management/export-class-student-status`,
  exportClassStudentTask: `${PREFIX}/api/exchange/page/class/management/export-class-student-task`
};
